branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  Sample-env:
    branch: null
    repository: null
global:
  application_name: IF5-Panel
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/PHP 7.0 running on
    64bit Amazon Linux/2.3.2
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
